 - name: install httpd package (Fedora)
   tags: apache,Fedora,httpd
   dnf:
     name:
       - httpd
       - php
     state: latest
   when: ansible_distribution == "Fedora"
 
 - name: start and enable httpd (Fedora)
   tags: apache,Fedora,httpd
   service:
     name: httpd
     state: started
     enabled: yes
   when: ansible_distribution == "Fedora"
 
 - name: install apache2 package (Ubuntu)
   tags: apache,apache2,ubuntu
   apt:
     name:
       - "{{ apache_package_name }}"
       - "{{ php_package_name }}"
     state: latest
   when: ansible_distribution == "Ubuntu"
 
 - name: change e-mail address for admin
   tags: apache,Fedora,httpd
   lineinfile:
     path: /etc/httpd/conf/httpd.conf
     regexp: '^ServerAdmin'
     line: ServerAdmin chaqchaq.hamza@proton.me
   when: ansible_distribution == "Fedora"
   notify: restart_apache
 
 - name: copy html file for site
   tags: apache,apache,apache2,httpd
   copy:
     src: default_site.html
     dest: /var/www/html/index.html
     owner: root
     group: root
     mode: 0644