- name: install unzip
  package:
    name: unzip
- name: download terraform
  get_url:
    url: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
    dest: /tmp/terraform_0.12.28_linux_amd64.zip
    mode: 0644
- name: install terraform
  unarchive:
    src: /tmp/terraform_0.12.28_linux_amd64.zip
    dest: /usr/local/bin
    mode: 0755
    owner: root
    group: root
    remote_src: yes